/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.com.unesp.uml_converter.presentation;

import br.com.unesp.uml_converter.models.BaseProject;
import br.com.unesp.uml_converter.utils.ArquivoUtils;
import br.com.unesp.uml_converter.utils.GsonUtils;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class UmlConverter extends javax.swing.JFrame {
    
    String json = ArquivoUtils.leitura("C:\\Users\\danie\\Documents\\faculdade\\unesp\\uml-converter\\uml-converter\\src\\main\\java\\br\\com\\unesp\\uml_converter\\presentation\\mock.json");
    BaseProject project = (BaseProject) GsonUtils.xmlToObjeto(json, BaseProject.class);

    /** Creates new form UmlConverter */
    public UmlConverter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogObject = new javax.swing.JDialog();
        jDialogAttributes = new javax.swing.JDialog();
        jDialogRelationship = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabelProjectTitle = new javax.swing.JLabel();
        jLabelProjectField = new javax.swing.JLabel();
        jLabelObjectsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListObjects = new javax.swing.JList<>();
        jButtonAddObjects = new javax.swing.JButton();
        jButtonRemoveObjects = new javax.swing.JButton();
        jLabelAttributesTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAttributes = new javax.swing.JList<>();
        jButtonRemoveAttribute = new javax.swing.JButton();
        jButtonAddAttribute = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNewProject = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuImport = new javax.swing.JMenu();
        jMenuItemImportJson = new javax.swing.JMenuItem();
        jMenuExport = new javax.swing.JMenu();
        jMenuItemExportJson = new javax.swing.JMenuItem();
        jMenuItemExportUml = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialogObjectLayout = new javax.swing.GroupLayout(jDialogObject.getContentPane());
        jDialogObject.getContentPane().setLayout(jDialogObjectLayout);
        jDialogObjectLayout.setHorizontalGroup(
            jDialogObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogObjectLayout.setVerticalGroup(
            jDialogObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialogAttributesLayout = new javax.swing.GroupLayout(jDialogAttributes.getContentPane());
        jDialogAttributes.getContentPane().setLayout(jDialogAttributesLayout);
        jDialogAttributesLayout.setHorizontalGroup(
            jDialogAttributesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogAttributesLayout.setVerticalGroup(
            jDialogAttributesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialogRelationshipLayout = new javax.swing.GroupLayout(jDialogRelationship.getContentPane());
        jDialogRelationship.getContentPane().setLayout(jDialogRelationshipLayout);
        jDialogRelationshipLayout.setHorizontalGroup(
            jDialogRelationshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogRelationshipLayout.setVerticalGroup(
            jDialogRelationshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Project"));

        jLabelProjectTitle.setText("Project name:");

        jLabelProjectField.setText("Locadora");

        jLabelObjectsTitle.setText("Objects:");

        jScrollPane1.setViewportView(jListObjects);

        jButtonAddObjects.setText("-");

        jButtonRemoveObjects.setText("+");
        jButtonRemoveObjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveObjectsActionPerformed(evt);
            }
        });

        jLabelAttributesTitle.setText("Attributes:");

        jListAttributes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jListAttributes);

        jButtonRemoveAttribute.setText("-");

        jButtonAddAttribute.setText("+");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText(">");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabelProjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelProjectTitle)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelObjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonAddObjects)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonRemoveObjects))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addComponent(jLabel6)
                            .addGap(48, 48, 48)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonRemoveAttribute)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonAddAttribute))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelAttributesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(24, 24, 24)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjectField)
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelProjectTitle)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelObjectsTitle)
                        .addComponent(jLabelAttributesTitle))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jLabel6)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonRemoveObjects)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRemoveAttribute)
                            .addComponent(jButtonAddAttribute))
                        .addComponent(jButtonAddObjects))
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");

        jMenuItemNewProject.setText("New Project...");
        jMenuItemNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewProjectActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNewProject);

        jMenuItemSaveAs.setText("Save as");
        jMenu1.add(jMenuItemSaveAs);
        jMenu1.add(jSeparator1);

        jMenuImport.setText("Import");

        jMenuItemImportJson.setText("From Json...");
        jMenuItemImportJson.setActionCommand("Import Project (.json)");
        jMenuItemImportJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportJsonActionPerformed(evt);
            }
        });
        jMenuImport.add(jMenuItemImportJson);

        jMenu1.add(jMenuImport);

        jMenuExport.setText("Export");

        jMenuItemExportJson.setText("To Json...");
        jMenuItemExportJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExportJsonActionPerformed(evt);
            }
        });
        jMenuExport.add(jMenuItemExportJson);

        jMenuItemExportUml.setText("To UML...");
        jMenuExport.add(jMenuItemExportUml);

        jMenu1.add(jMenuExport);
        jMenu1.add(jSeparator2);

        jMenuItemExit.setText("Exit");
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemImportJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportJsonActionPerformed
        // TODO add your handling code here:
        DefaultListModel listModel = new DefaultListModel();
        
        List<String> objectNames = project.getObjects().stream().map(mo -> mo.getObjectName()).collect(Collectors.toList());
        listModel.addAll(objectNames);
        
        jListObjects.setModel(listModel);
                
        jListObjects.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                List<String> attributes = project.getObjects().get(jListObjects.getSelectedIndex()).getAttributes().stream().map(mo -> mo.toString()).collect(Collectors.toList());
                DefaultListModel listModel2 = new DefaultListModel();
                listModel2.addAll(attributes);

                jListAttributes.setModel(listModel2);
            }
        });
           

        
    }//GEN-LAST:event_jMenuItemImportJsonActionPerformed

    private void jButtonRemoveObjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveObjectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveObjectsActionPerformed

    private void jMenuItemExportJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExportJsonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExportJsonActionPerformed

    private void jMenuItemNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewProjectActionPerformed
        // TODO add your handling code here:
        jDialogObject.pack();
        jDialogObject.setLocationRelativeTo(null);
        jDialogObject.setVisible(true);
    }//GEN-LAST:event_jMenuItemNewProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UmlConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UmlConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UmlConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UmlConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                var frame = new UmlConverter();
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAttribute;
    private javax.swing.JButton jButtonAddObjects;
    private javax.swing.JButton jButtonRemoveAttribute;
    private javax.swing.JButton jButtonRemoveObjects;
    private javax.swing.JDialog jDialogAttributes;
    private javax.swing.JDialog jDialogObject;
    private javax.swing.JDialog jDialogRelationship;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAttributesTitle;
    private javax.swing.JLabel jLabelObjectsTitle;
    private javax.swing.JLabel jLabelProjectField;
    private javax.swing.JLabel jLabelProjectTitle;
    private javax.swing.JList<String> jListAttributes;
    private javax.swing.JList<String> jListObjects;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExport;
    private javax.swing.JMenu jMenuImport;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemExportJson;
    private javax.swing.JMenuItem jMenuItemExportUml;
    private javax.swing.JMenuItem jMenuItemImportJson;
    private javax.swing.JMenuItem jMenuItemNewProject;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
